server:
  port: 8081
  servlet:
    context-path: /train-reservation

spring:
  datasource:
    url: jdbc:h2:mem:train_reservation
    username: sa
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true

logging:
  level:
    sql: debug

